### ISSUE TITLE
趙元任粵語羅馬字

### ISSUE THREAD

**Issue by chowhoyin** [tanxpyox/rime-cantonese-schemes#1]
想體驗…😳

**Comment by laubonghaudoi** [comment]
> 其實我係想真係用粵羅嚟打字，唔係打粵拼顯示粵羅。不過都係多謝你~

即係話你想攞個新嘅拼音方案嚟打字？我哋肯定唔鼓勵，粵拼係粵語嘅標準拼音方案，有得用粵拼打字就用粵拼

**Comment by chowhoyin** [comment]
> er。。。噉我遲啲再搞過。。。
> 
> 下次記得將個issue擺去 [CanCLID/rime-cantonese-schemes](https://github.com/CanCLID/rime-cantonese-schemes) 嘞

其實已經有人做咗，你有興趣嘅話可以去睇睇~
https://github.com/Chingyat/rime-yutlo

**Comment by tanxpyox** [comment]
:+1:
