### ISSUE TITLE
劉錫祥方案 vs 耶魯拼音 ?

### ISSUE THREAD

**Issue by DonaldTsang** [tanxpyox/rime-cantonese-schemes#2]
Which is better for those that speak English, whilst maintaining the phonetic consistency of Cantonese?

**Comment by tanxpyox** [comment]
Hi! For English speakers, I reckon 劉錫祥 (Sidney Lau) is an easier start - but we would always recommend **Jyutping** as your go-to, as most Cantonese resources are only available in that format. (and we are trying our best to popularise it)

**Comment by DonaldTsang** [comment]
Academic form (Jyutping) and Common forms (S. Lau/Yale/Edu) have vastly different use cases.
And I sincerely hope that in order for the general masses to adapt to Cantonese they should use Common forms.

If there is a sed file for it, that would be great.

**Comment by tanxpyox** [comment]
We don't believe it is appropriate to make the academic-common distinction anymore - for every language (e.g. Japanese, Thai, Mandarin etc), having a universal and consistent romanisation scheme is elementary to its survival. Also, we feel that the other romanisation schemes are unable to represent dialect-specific phonemes for parts of Guangdong and Guangxi, which would simply pose an unnecessary obstacle to Cantonese preservation. (e.g. in the Guangzhou-Hong Kong dialect: 'gep6' as in 「夾」公仔 and 'deu6' as in 「掉」垃圾 are not transliterable in those "common" forms)

You can check out our reasoning in full [here](https://www.jyutping.org/blog/scheme/) and my sed scripts [here](https://github.com/CanCLID/rime-cantonese-alt-dict/tree/master/scripts)

PS: Personally, I didn't find it challenging at all to learn Jyutping - it took me just 2 hours to read up the manual and I was all set.
